CREATE TABLE IF NOT EXISTS td_ext_anp.codigos_instalacao (
	cod_instalacao STRING,
	num_cnpj STRING,
	nom_razao_social STRING,
	num_cep STRING,
	nom_titulo STRING,
	txt_endereco STRING,
	num_numero STRING,
	txt_complemento STRING,
	nom_bairro STRING,
	nom_municipio STRING,
	nom_estado STRING,
	num_autorizacao STRING,
	dat_publicacao STRING,
	txt_status STRING,
	txt_tipo_instalacao STRING,
	txt_identificacao_instalacao STRING,
	nom_reduzido STRING,
	num_cnpj_administrador_base STRING,
	dat_mesano_vigencia_inicial STRING,
	dat_mesano_vigencia_final STRING,
	data_versao STRING,
	data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) PARTITION BY DATE(data_criacao);