CREATE TABLE IF NOT EXISTS td_ext_anp.codigos_instalacao (
	cod_instalacao NUMERIC,
	num_cnpj STRING,
	nom_razao_social STRING,
	num_cep NUMERIC,
	txt_endereco STRING,
	num_numero NUMERIC,
	txt_complemento STRING,
	nom_bairro STRING,
	nom_municipio STRING,
	nom_estado STRING,
	num_autorizacao STRING,
	dat_publicacao DATE,
	txt_status STRING,
	txt_tipo_instalacao STRING,
	nom_reduzido STRING,
	num_cnpj_administrador_base STRING,
	dat_mesano_vigencia_inicial DATE,
	dat_mesano_vigencia_final DATE,
	data_versao TIMESTAMP,
	data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) PARTITION BY DATE(data_criacao);