CREATE TABLE IF NOT EXISTS td_ext_anp.postos_revendedores (
    id INT64 OPTIONS(description="Identificador único do registro."),
	numero_autorizacao STRING OPTIONS(description="Número da autorização"),
	data_publicacao_dou_autorizacao DATE OPTIONS(description="Data de publicação no DOU da autorização"),
	codigo_instalacao_i_simp STRING OPTIONS(description="Código da instalação (I-SIMP)"),
	razao_social STRING OPTIONS(description="Razão social do posto"),
	cnpj STRING OPTIONS(description="CNPJ do posto"),
	endereco STRING OPTIONS(description="Endereço do posto"),
	complemento STRING OPTIONS(description="Complemento do posto"),
	bairro STRING OPTIONS(description="Bairro do posto"),
	cep STRING OPTIONS(description="CEP do posto"),
	uf STRING OPTIONS(description="UF do posto"),
	municipio STRING OPTIONS(description="Município do posto"),
	vinculacao_a_distribuidor STRING OPTIONS(description="Vinculação a Distribuidor"),
	data_de_vinculacao_a_distribuidor DATE OPTIONS(description="Data de vinculação a Distribuidor"),
	produto STRING OPTIONS(description="Produto"),
	tancagem_m3 NUMERIC OPTIONS(description="Tancagem (m³)"),
	qtde_de_bico NUMERIC OPTIONS(description="Quantidade de bico"),
	latitude STRING OPTIONS(description="Latitude"),
	longitude STRING OPTIONS(description="Longitude"),
	delivery STRING OPTIONS(description="Delivery"),
	data_autorizacao_delivery DATE OPTIONS(description="Data de autorização do delivery"),
	numero_despacho_delivery STRING OPTIONS(description="Número do despacho do delivery"),
	status_pmqc STRING OPTIONS(description="Status PMQC"),
	data_criacao TIMESTAMP OPTIONS(description="Data de criação do registro na camada raw"),
	data_ingestao_td TIMESTAMP DEFAULT CURRENT_TIMESTAMP() OPTIONS(description="Data de criação do registro na camada trusted")
) PARTITION BY DATE(data_ingestao_td);
