<<<<<<<< HEAD:src/market_share/liquidos_vendas_atual/Dockerfile
FROM python:3.9-slim

WORKDIR /app

COPY . .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

CMD ["python3", "rw_liquidos_vendas_atual.py"]
========
FROM python:3.9-slim

WORKDIR /app

COPY . .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

CMD ["python3", "rw_ext_anp_codigos_instalacao.py"]
>>>>>>>> develop:src/manual_simp/codigos_instalacao/Dockerfile
